
Meteor.startup(function(){

var insertItems = [ { _id: '262b79bLHQfuEKiCq',
    chefId: 'GfeKy92bg4y5KdJo4',
    rand: 0.5336252788547426,
    title: 'Karask juustuvahu, tomati ja chilliga',
    formErrors: {},
    ingredients: 'Kohupiim, odrajahu, või, muna, juust, toorjuust, chilli',
    foodType: 'main',
    weight: 35,
    published: true,
    price: 0.8 },
  { _id: '2DRPAjs9nZL4jgJSY',
    chefId: 'GfeKy92bg4y5KdJo4',
    rand: 0.5779101473744959,
    title: 'Shampinjonid tomati ja sinihallitusjuustuga tumedal ciabattal',
    formErrors: {},
    ingredients: 'Shampinjonid, tomat, sinihallitusjuust, balsamico, ciabatta',
    foodType: 'main',
    weight: 35,
    published: true,
    price: 0.8 },
  { _id: '2WrFEyZPwkSXnBTMW',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.9066906468942761,
    title: 'Köögiviljapirukas kartuli-rukkijahu põhjal ',
    foodType: 'main',
    ingredients: 'Või, jahu, kartul, munad, rõõsk koor, juust, porgand, sibul, porru, paprika, maitseained',
    published: true,
    formErrors: {},
    weight: 80,
    price: 1.1 },
  { _id: '3GoRp4actKCSsy77Q',
    chefId: 'GXuYGobJtJq5THiZh',
    title: 'Õrnsoolatud kalafilee munakreemiga krõbedas wonton korvis',
    formErrors: {},
    ingredients: 'Kalafilee, muna, majonees, ürdid, jahu, või, maitseained',
    foodType: 'main',
    weight: 40,
    published: true,
    price: 0.8 },
  { _id: '3p2EGtjuD9xCxc8gH',
    chefId: 'GXuYGobJtJq5THiZh',
    rand: 0.23707150854170322,
    title: 'Kirju koer',
    formErrors: {},
    ingredients: 'Küpsis, või, kondenspiim, kakao, shokolaad, rosinad, pähklid, brändi, aprikoos',
    foodType: 'dessert',
    weight: 60,
    published: true,
    price: 0.8 },
  { _id: '3pX97QsbRLnhdaRQ4',
    chefId: 'WQzN4N8LdwBNGzzZ5',
    rand: 0.17579990695230663,
    title: 'Täisterakaerahelbe küpsis kakao ja pisukese laimiga',
    formErrors: {},
    ingredients: 'Täisterakaerahelbejahu, majonees, pruun suhkur, sooda, kakao, laim',
    foodType: 'dessert',
    weight: 30,
    published: true,
    price: 0.8 },
  { _id: '4EMS7SYhSZ2CgtSmp',
    chefId: 'WQzN4N8LdwBNGzzZ5',
    rand: 0.33314338442869484,
    title: 'Vanakooli rabarberi plaadikook',
    formErrors: {},
    ingredients: 'Nisujahu, muna, või, suhkur, rabarber, kartulijahu, küpsetuspulber',
    price: 1.1,
    weight: 80,
    foodType: 'dessert',
    published: true },
  { _id: '4zjnRM5snsee8w5rY',
    chefId: 'GfeKy92bg4y5KdJo4',
    rand: 0.11872891103848815,
    title: 'Sibula toorjuustu kook',
    formErrors: {},
    ingredients: 'Sibul, rukkijahu, või, sool, juust, toorjuust',
    foodType: 'main',
    weight: 35,
    published: true,
    price: 0.9},
  { _id: '5Q3pxwiJa5v9zcFpc',
    chefId: 'GXuYGobJtJq5THiZh',
    rand: 0.2741938659455627,
    title: 'Lastemenüü 110€ (a\'20tk)',
    formErrors: {},
    ingredients: '1. Konn Krooks miniburger (kodune kakuke, hakkliha, salatileht, tomativiil, juust, kaste)\n2. Kaheksajalad ründavad (viineritest kaheksajalad, kodune kartulisalat või makaronisalat, serveering eraldi topsides)\n3. Krõbedad kahurikuulid (juustupallid, kaste)\n4. Värvilised vägipulgad (paprika, valge redis, porgand, värske kurk, kaste, serveering eraldi topsis)\n5. Kama Artur pallid (kamapallid, iiris, või, shokolaad)\n6. Vihmaussipidu (tarretis, vihmaussi kummikomm)',
    weight: 250,
    foodType: 'main',
    published: true,
    price: 1.1 },
  { _id: '5QPb6FkvtFezPwWeb',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.7469299715012312,
    title: 'Krõbedad juustu-pesto kolmnurgad',
    formErrors: {},
    ingredients: 'Lehttainas, pesto, maitseained, õli, juust',
    foodType: 'main',
    price: 0.5,
    weight: 15,
    published: true},
  { _id: '5m3vrHSgPSkfDkuti',
    chefId: 'GfeKy92bg4y5KdJo4',
    rand: 0.5744204102084041,
    title: 'Klassikalised täidetud munad',
    formErrors: {},
    ingredients: 'Muna, või, maitserohelist, sool, pipar',
    foodType: 'main',
    weight: 25,
    published: true,
    price: 0.8 },
  { _id: 'AR6Mw3xtP7xENvgGq',
    chefId: 'nz33rNfKj6htGmFTv',
    rand: 0.6270959156099707 },
  { _id: 'G2e4pZxipdB74jt8L',
    chefId: 'Knq5BxiP3qfnMT52Q' },
  { _id: '5rqxCk9KkEGh65yvD',
    chefId: 'WQzN4N8LdwBNGzzZ5',
    rand: 0.5018714745528996,
    title: 'Lavashirull tuunikalaga',
    formErrors: {},
    ingredients: 'Täisterajahust lavash, tuunikala konserv, hapukoor, majonees, sibul, sulajuust, lehtsalat',
    foodType: 'main',
    price: 1.1,
    weight: 30,
    published: true },
  { _id: '66jcXJNAP37qvJnuc',
    chefId: 'GXuYGobJtJq5THiZh',
    rand: 0.42722639231942594,
    title: 'Juustupallid ',
    formErrors: {},
    ingredients: 'Juust, muna, seesamiseemned, riivsai, maitseained, jahu',
    foodType: 'main',
    weight: 25,
    published: true,
    price: 0.8 },
  { _id: '67ZJmnZrAptGc8iRo',
    chefId: 'vW7xv5Ckjmy2wSbie',
    rand: 0.6533397836610675,
    title: 'Puuviljavaagen',
    formErrors: {},
    ingredients: 'Hele viinamari, tume viinamari, apelsin, kiivi, pirn',
    foodType: 'dessert',
    weight: 3,
    price: 25,
    published: true },
  { _id: '6ApFo3QXkZRW894Q5',
    chefId: 'GfeKy92bg4y5KdJo4',
    rand: 0.8441548594273627,
    title: 'Spinati-lillkapsa-brokkoli-porru- kodujuustu individuaalne koogike',
    formErrors: {},
    ingredients: 'Spinati, lillkapsa, brokkoli, porru, kodujuust, muna, juust',
    foodType: 'main',
    price: 1.3,
    weight: 35,
    published: true },
  { _id: '6dTY8QyejuR6WJWx2',
    chefId: 'fwRMoa93LcF3PjvoP',
    rand: 0.3133363761007786,
    title: 'Vegan kartulisalati-korvike',
    formErrors: {},
    ingredients: 'Kartul, porgand, kurk, hernes, sojajogurt, nisujahu',
    foodType: 'main',
    weight: 30,
    published: true,
    price: 0.8 },
  { _id: '7csGd2LbNeit7BLmM',
    chefId: 'WQzN4N8LdwBNGzzZ5',
    rand: 0.8752236946020275,
    title: 'Kodused Bounty pallid tumeda shokolaadiga',
    formErrors: {},
    ingredients: 'Kookoshelbed, kondenspiim, tumeshokolaad',
    price: 0.8,
    weight: 30,
    foodType: 'dessert',
    published: true },
  { _id: '7fHBTHL8KQxXtZhfn',
    chefId: 'GXuYGobJtJq5THiZh',
    title: 'Profitroolid hõrgu suitsukala ja bulgurisalatiga',
    formErrors: {},
    ingredients: 'Jahu, muna, või, suitsukala, bulgur, paprika, kurk, mais, ürdid, majonees, maitseained',
    foodType: 'main',
    weight: 70,
    published: true,
    price: 1.1 },
  { _id: '7qktsL8x5eN5JsfHa',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.4119099194649607,
    title: 'Koduse seemneleiva kolmnurgad talusingi ja ürdivõiga',
    ingredients: 'Leib (juuretis, suhkur, sool, erinevad seemned ja rosinad), ürdivõi, veiselihast talusink',
    foodType: 'main',
    published: true,
    formErrors: {},
    weight: 40,
    price: 1.1 },
  { _id: '7uRb6pjhYCFszHuC5',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.5202206522226334,
    title: 'Mini-quiche porru ja peekoniga',
    formErrors: {},
    ingredients: 'Muretainas, peekon, sibul, porru, koor, muna, juust, maitseained, tomat',
    price: 1.1,
    foodType: 'main',
    weight: 45,
    published: true },
  { _id: '88zJdpME2nv6hxM3n',
    chefId: 'GXuYGobJtJq5THiZh',
    rand: 0.39845147053711116,
    title: 'Kalatort maitserohelise konsomeega',
    formErrors: {},
    ingredients: 'Must leib, heeringas, või, sibul, hapukoor, kodujuust, zelatiin, maitseroheline, maitseained',
    foodType: 'main',
    weight: 50,
    published: true,
    price: 0.8 },
  { _id: '8Pj7DiFgNyTTaRWqc',
    chefId: 'GXuYGobJtJq5THiZh',
    title: 'Värviküllane heeringatort peedi-,maitserohelise- ja toorjuustuvahuga',
    formErrors: {},
    ingredients: 'Õrnsoolaheeringas, leib, muna, peet, ürdid, majonees, toorjuust, või, kirsstomat, maitseained',
    foodType: 'main',
    weight: 60,
    published: true,
    price: 0.8 },
  { _id: '8qSAumTM3d9cSH4Df',
    chefId: 'vW7xv5Ckjmy2wSbie',
    rand: 0.0634232780430466,
    title: 'Sinihallitusjuustu seemneleival',
    formErrors: {},
    ingredients: 'Sinihallitusjuustu-toorjuustukreem, seemneleib, maitseroheline',
    foodType: 'main',
    price: 1,
    weight: 30,
    published: true },
  { _id: '8qhqQ7aZAtXXGFoep',
    chefId: 'GfeKy92bg4y5KdJo4',
    title: 'Kodune pasteet kodusel kukklil punasesõstra-sibula moosiga',
    formErrors: { managerComments: 'Palun täida ka see väli' },
    ingredients: 'Jahu, pärm, või, vesi, sool, suhkur, seamaks ja -liha või kanamaks, konjak, pipar, muskaat, punased sõstrad, sibul, õun, ingver, chilli.',
    foodType: 'main',
    weight: 30,
    published: true,
    managerComments: '',
    price: 1.1},
  { _id: '8qwXHSTanfk5oWkbh',
    chefId: 'vW7xv5Ckjmy2wSbie',
    title: 'Kikerhernehummus seemneleival',
    formErrors: {},
    ingredients: 'Kikerherned, küüslauk, sidrun, vürtsköömned, seesamiseemned, oliiviõli, tahiinipasta, maitseroheline',
    foodType: 'main',
    weight: 40,
    published: true,
    price: 1,
    managerComments: ''},
  { _id: '8vbT4LTSi6MD4pGBp',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.32501366757787764,
    title: 'Krõbisevad šokolaadiruudud',
    formErrors: {},
    ingredients: 'Riisikrõbinad, šokolaad, või, iirised',
    foodType: 'dessert',
    price: 0.9,
    weight: 25,
    published: true },
  { _id: '9EonbK4vCcHRCJwaa',
    chefId: 'GfeKy92bg4y5KdJo4',
    rand: 0.2599847454112023,
    title: 'Kama trühvlid kuivatatud jõhivikatega shokolaadi kaunistusega',
    formErrors: {},
    ingredients: 'Kama, toorjuust, kuivatatud jõhvikad, tume shokolaad, mesi',
    foodType: 'dessert',
    weight: 20,
    published: true,
    price: 0.8 },
  { _id: '9XfiXqb3BConackiL',
    chefId: 'GfeKy92bg4y5KdJo4',
    title: 'Sinihallitusjuutsu vaht kodusel juuretisega saial pirni ja chilliga',
    formErrors: {},
    ingredients: 'Nisu täisterajahu, juuretis, vesi, suhkur, sool, muskaat, ingver, sinihallitusjuust, toorjuust, pirn, chilli.',
    foodType: 'main',
    weight: 30,
    published: true,
    price: 1.1},
  { _id: '9ijCZJLDRHCe8tgAD',
    chefId: 'WQzN4N8LdwBNGzzZ5',
    rand: 0.5076146414503455,
    title: 'Kõrvitsasai',
    formErrors: {},
    ingredients: 'Jahu, muna, või, sool, suhkur, pärm, piim, kõrvits, kõrvitsaseemned',
    foodType: 'main',
    weight: 30,
    published: true,
    price: 0.8,
    managerComments: '' },
  { _id: '9vg6QP6iyvkF6eWeY',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.06062197941355407,
    title: 'Kama-leivatort mustikatega',
    ingredients: 'Rukkileib, suhkur, või, kohupiim, hapukoor, suhkur, kamajahu, mustikad, želatiin',
    foodType: 'dessert',
    weight: 60,
    published: true,
    formErrors: {},
    price: 1.5 },
  { _id: 'AkvwxoCA6QESf3JJA',
    chefId: 'vW7xv5Ckjmy2wSbie',
    rand: 0.15069456840865314,
    title: 'Tartalett värskete marjade, mündi ja vaarikakreemiga',
    formErrors: {},
    ingredients: 'Tartalett, vaarikakreem, marjad, münt',
    foodType: 'dessert',
    price: 1.3,
    weight: 50,
    published: true },
  { _id: 'BPmbXHAFsodxCFbkP',
    chefId: 'GXuYGobJtJq5THiZh',
    title: 'Mozzarella tikud kirsstomatite, basiiliku ja oliividega',
    formErrors: {},
    ingredients: 'Mozzarella juust, kirsstomatid, basiilik, must oliiv',
    foodType: 'main',
    weight: 25,
    published: true,
    price: 0.8 },
  { _id: 'BQEjkiTxqNexHisMJ',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.9733028633054346,
    title: 'Krõbe šokolaadi-maisihelbe kook',
    formErrors: {},
    ingredients: 'Maisihelbed, või, šokolaad, suhkur',
    foodType: 'dessert',
    price: 0.9,
    weight: 45,
    published: true },
  { _id: 'BnvwQGpsxKdWQAFpM',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.6940265314187855,
    title: 'Õuna-iirise kook ',
    ingredients: 'Küpsised, või, fariinisuhkur, õunad, toorjuust, hapukoor, munad, iirised, suhkur, purustatud mandlid',
    foodType: 'dessert',
    published: true,
    formErrors: {},
    weight: 45,
    price: 1.1 },
  { _id: 'BpaigjbvEwsYqTMzA',
    chefId: 'vW7xv5Ckjmy2wSbie',
    rand: 0.6539597860537469,
    title: 'Anšoovise-toorjuustuvaht seemneleival',
    formErrors: {},
    ingredients: 'Anšoovise-toorjuustuvaht, maitseroheline, seemneleib',
    foodType: 'main',
    price: 1,
    weight: 30,
    published: true },
  { _id: 'CKz2FGr5JRWFnHb5q',
    chefId: 'GfeKy92bg4y5KdJo4',
    rand: 0.6503906734287739,
    title: 'Kartulisalat einesingiga',
    formErrors: {},
    foodType: 'main',
    price: 8,
    weight: 1000,
    ingredients: 'Kartul, porgand, hapukurk, muna, hernes, einesink, sool, pipar, majonees, hapukoor',
    published: true },
  { _id: 'CTAjXm3gTvNaP2CP2',
    chefId: 'vW7xv5Ckjmy2wSbie',
    title: '\nLõhe-rõikakreem meremarjaga lavašikorvis',
    formErrors: {},
    ingredients: 'Lõhe, rõika-toorjuustukreem, lavašikorvike, meremari, maitseroheline',
    foodType: 'main',
    weight: 40,
    published: true,
    price: 1.5},
  { _id: 'CeKsQ7xBjwDKpPKjy',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.34410583251155913,
    title: 'Banaani-šokolaadi muffinid pähklitega',
    ingredients: 'Nisu- või täistera nisujahu, või, küpsetuspulber, suhkur, banaan, tume šokolaad, pähklid, muna',
    foodType: 'dessert',
    published: true,
    formErrors: {},
    weight: 40,
    price: 1.1 },
  { _id: 'DMcxxNwvowTGeDnWr',
    chefId: 'GfeKy92bg4y5KdJo4',
    rand: 0.06738236942328513,
    title: 'Vürtsikilu-munavõidega täidetud munad meremarjaga',
    formErrors: {},
    ingredients: 'Muna, või, vürtsikilu, meremari',
    foodType: 'main',
    weight: 25,
    published: true,
    price: 0.8 },
  { _id: 'DQPfFKZ7J7cNGuaR2',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.6259540668688715,
    title: 'Juustu muffinid päikesekuivatatud tomatitega',
    formErrors: {},
    ingredients: 'Jahu, või/õli, munad, hapukoor, piim, maitseained, juust, päikesekuivatatud tomatid, seemned',
    foodType: 'main',
    price: 0.8,
    weight: 55,
    published: true },
  { _id: 'DwTt5eLYi9WiJfTuz',
    chefId: 'GXuYGobJtJq5THiZh',
    ingredients: 'Looma-ja seahakkliha, muna, jahu, ürdid, salatileht, juust, kirsstomat, kurk, idandid, sinep, kaste',
    formErrors: {},
    title: 'Miniburger',
    foodType: 'main',
    weight: 70,
    published: true,
    price: 1.1 },
  { _id: 'E9TrW9epWsfQmWfnd',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.1895313838031143,
    title: 'Suitsukana-ricotta muffinid',
    formErrors:
     { title: null,
       ingredients: null,
       foodType: null },
    ingredients: 'Jahu, või/õli, munad, ricotta kohupiim, piim, maitseained, juust, ürdid.',
    foodType: 'main' },
  { _id: 'EEzaFmKHSLF5jaBA9',
    chefId: 'WQzN4N8LdwBNGzzZ5',
    rand: 0.6455541157629341,
    title: 'Pannkoogid koduse õunamoosiga',
    formErrors: {},
    ingredients: 'Talupiim, talumunad, nisujahu, pruun suhkur, kodune õunamoos',
    foodType: 'dessert',
    weight: 30,
    published: true,
    price: 0.5},
  { _id: 'EfPrt5tKuvbdZnAmQ',
    chefId: 'GXuYGobJtJq5THiZh',
    rand: 0.98090805625543,
    title: 'Lavashirull singi ja juustuga',
    formErrors: {},
    ingredients: 'Sink, juust, helmanns majonees, paprika, kurk, lavash, sinep, salat',
    foodType: 'main',
    weight: 50,
    published: true,
    price: 1.1 },
  { _id: 'FHazRZyL94wDJiMLA',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.5092967122327536,
    title: 'šokolaadi-kohvi juustukook',
    ingredients: 'Küpsised, või, suhkur, toorjuust, munad, suhkur, šokolaad, želatiin, kohvi',
    foodType: 'dessert',
    weight: 70,
    published: true,
    price: 1.5 },
  { _id: 'FTA3oSnREqMMSkwSA',
    chefId: 'vW7xv5Ckjmy2wSbie',
    title: 'Röstpeedi-küüslaugu-fetajuustu lavašikorvis',
    formErrors: {},
    ingredients: 'Peet, feta, küüslauk, lavašikorvike, maitseroheline',
    foodType: 'main',
    weight: 40,
    published: true,
    price: 1},
  { _id: 'FnuaDyxpvkf44abPp',
    chefId: 'GXuYGobJtJq5THiZh',
    title: 'Profitroolid täidetud värskete ürtide- ja juustukreemiga',
    formErrors: {},
    ingredients: 'Jahu, muna, või, ürdid, juust, majonees, maitseained',
    foodType: 'main',
    weight: 35,
    published: true,
    price: 0.8 },
  { _id: 'GJawJPTkysnesTPBC',
    chefId: 'GfeKy92bg4y5KdJo4',
    weight: 25,
    formErrors: {},
    foodType: 'main',
    title: 'Vürtsikiluvõie meremarjaga kodusel seemnetega rukkileival',
    ingredients: 'Täistera seemnetega rukkileib (juuretisega), vürtsikilu, või, meremari.',
    published: true,
    price: 0.8 },
  { _id: 'GYPbnvSY8Beu4X3g7',
    chefId: 'GfeKy92bg4y5KdJo4',
    rand: 0.559476243564859,
    title: 'Kodune kanamaksa-rukkinööp koduse punase sõstra-sibula moosiga',
    formErrors: {},
    ingredients: 'kanamaks, või, rukkinööp, moos',
    foodType: 'main',
    price: 0.8,
    weight: 30,
    published: true },
  { _id: 'Gfc6yRyugFFryNkrZ',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.33632982219569385,
    title: 'Muskaadine kõrvitsakook piparkoogise põhja ja mandlilaastu katusega',
    formErrors: {},
    ingredients: 'Piparkoogid, või, suhkur, kõrvits, toorjuust, mandlilaastud, maitseained',
    foodType: 'dessert',
    weight: 40,
    published: true,
    price: 0.8 },
  { _id: 'GfquPtmrf5BPGqRQr',
    chefId: 'GfeKy92bg4y5KdJo4',
    rand: 0.7615627574268728,
    title: 'Coppa sink terava toorjuustuvahul viinamarjaga lavashi korvis',
    formErrors: {},
    ingredients: 'Coppa vinnutatud sink, toorjuust, pipar, viinamarjad, lavash',
    foodType: 'main',
    price: 1.5,
    weight: 35,
    published: true },
  { _id: 'Gm8kZY95sbdKTsGdE',
    chefId: 'fwRMoa93LcF3PjvoP',
    rand: 0.5182753154076636,
    title: 'Vegan korvike',
    formErrors: {},
    ingredients: 'Köögiviljad, kirsstomatid, sojajogurt',
    foodType: 'main',
    weight: 30,
    published: true,
    price: 0.8 },
  { _id: 'GszPEy54gFdmZ4vsT',
    chefId: 'vW7xv5Ckjmy2wSbie',
    title: 'Kamakreem vahvlitopsis',
    formErrors: {},
    ingredients: 'Kama-toorjuustukreem, värsked marjad, vahvlitops,maitseroheline',
    foodType: 'dessert',
    weight: 60,
    published: true,
    price: 1.5},
  { _id: 'H59PpsqmZnGiHufAm',
    chefId: 'WQzN4N8LdwBNGzzZ5',
    rand: 0.4977897971402854,
    title: 'Täisterarukkijahu küpsised kuivatatud aprikooside ja ploomidega',
    formErrors: {},
    ingredients: 'Täisterarukkijahu, või, küpsetuspulber, pruun suhkur, muna, kuivatatud aprikoosid, kuivatatud ploomid',
    foodType: 'dessert',
    weight: 30,
    published: true,
    price: 0.8 },
  { _id: 'Hg48WXF9QTSbADAmQ',
    chefId: 'vW7xv5Ckjmy2wSbie',
    rand: 0.7929800162091851,
    title: 'Caesar kanaga lavašikorvis',
    formErrors: {},
    ingredients: 'caesari salat, kanafilee, maitseroheline, pk. tomat',
    weight: 50,
    foodType: 'main',
    published: true,
    price: 1.5},
  { _id: 'HhsBWaNmLdmxW9Awu',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.5592511179856956,
    title: 'Õuna-kaneeli roos',
    formErrors: {},
    foodType: 'dessert',
    price: 0.8,
    weight: 25,
    ingredients: 'Lehttainas, õun, kaneel, või, suhkur',
    published: true },
  { _id: 'Jh6uyqhkjqceugzRw',
    chefId: 'GfeKy92bg4y5KdJo4',
    rand: 0.7280296578537673,
    title: 'Oliivi-kappari pasta krõbedal prantsuse saial mozarella ja röstitud paprikaga',
    formErrors: {},
    ingredients: 'Oliivid, kapparid, balsamico, sai, mozarella, röstitud paprika.',
    weight: 35,
    price: 1.2,
    foodType: 'main',
    published: true },
  { _id: 'JqtETQNTsAjH8eAiC',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.251730524469167,
    title: 'Leht- või muretaignal spinati-sinihallitusjuustu plaadipirukas seemnekattes ',
    ingredients: 'Või, jahu, munad, spinat, sinihallitusjuust, juust, hapukoor, piim, maitseained, kõrvitsaseemned',
    foodType: 'main',
    published: true,
    weight: 45,
    formErrors: {},
    price: 0.8 },
  { _id: 'K99LWRajSg47665TW',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.9005952505394816,
    title: 'Suhkrupärlitega kaneelirullid',
    formErrors: {},
    ingredients: 'Pärmitainas, või, suhkur, kaneel',
    price: 0.9,
    foodType: 'dessert',
    weight: 30,
    published: true },
  { _id: 'KQJ9suTibaSSMmztB',
    chefId: 'GfeKy92bg4y5KdJo4',
    rand: 0.7008030565921217,
    title: 'Soolalõhe toorjuustuvahul ja kodusel kukklil',
    formErrors: {},
    ingredients: 'Soolalõhe, toorjuust, nisujahu kukkel, meremari, maisterohelist',
    foodType: 'main',
    weight: 35,
    published: true,
    price: 1.1 },
  { _id: 'LFnBTNJLrt5QL92XZ',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.2879390590824187,
    title: 'Juustukattes porru-peekoni plaadipirukas muretaignal',
    ingredients: 'Nisu- või täistera nisujahu, või, munad, peekon, porru, sibul, rõõskkoor, juust, toorjuust, maitseained',
    foodType: 'main',
    published: true,
    formErrors: {},
    weight: 40,
    price: 0.9},
  { _id: 'LwyLQ4vm8QxtvfCQh',
    chefId: 'WQzN4N8LdwBNGzzZ5',
    rand: 0.1222300089430064,
    title: 'Kirju koer tumeda shokolaadi, rosinate ja ohtra marmelaadiga',
    formErrors: {},
    ingredients: 'Küpsised, kakao, või, jogurt, tume shokolaad, rosinad, marmelaad',
    foodType: 'dessert',
    weight: 40,
    published: true,
    price: 0.8 },
  { _id: 'Y7F7QjYEpN9YKPq9G',
    chefId: 'MPbdoqo5kGLqsy8uh',
    rand: 0.7297800027299672 },
  { _id: 'MANxriA25awSAPFLe',
    chefId: 'GXuYGobJtJq5THiZh',
    rand: 0.5355396505910903,
    title: 'Kama Artur',
    formErrors: {},
    ingredients: 'Iiris, või, kamapallid',
    foodType: 'dessert',
    weight: 40,
    published: true,
    price: 0.8 },
  { _id: 'MnzahhMCjpMFvipeu',
    chefId: 'GXuYGobJtJq5THiZh',
    title: 'Käsitöökommid',
    formErrors: {},
    ingredients: 'Küpsis, toorjuust, shokolaad',
    foodType: 'dessert',
    weight: 30,
    published: true,
    price: 1.1},
  { _id: 'N3uYwmscJQwAzrcPr',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.616113722557202,
    title: 'Vimkaga viinerid pulga otsas',
    formErrors: {},
    ingredients: 'Viinerid, lehttainas',
    foodType: 'main',
    price: 0.6,
    weight: 25,
    published: true },
  { _id: 'PNbyHLsiYAPwQ5wpP',
    chefId: 'GXuYGobJtJq5THiZh',
    rand: 0.733168400125578,
    title: 'Juurviljad kastmega eraldi topsis',
    formErrors: {},
    ingredients: 'Paprika, valge redis, värske kurk, porgand, seller, kaste',
    foodType: 'main',
    weight: 30,
    published: true,
    price: 0.8 },
  { _id: 'Pz78WHiAPQfhThKjX',
    chefId: 'GfeKy92bg4y5KdJo4',
    rand: 0.3089923709630966,
    title: 'Täidetud munad munavahuvõie ja vürtsikiluga',
    formErrors: {},
    foodType: 'main',
    weight: 30,
    ingredients: 'Muna, või, toorjuust, vürtsikilu, meremari, maitseroheline, sool, pipar',
    published: true,
    price: 1.1 },
  { _id: 'Q5TwhhF5mwQprBbkf',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.9103363365866244,
    title: 'Lavašikrõpsud juustuga (värvilistes torbikutes)',
    formErrors: {},
    ingredients: 'Lavaš, juust, maitseained',
    price: 0.8,
    foodType: 'main',
    weight: 30,
    published: true },
  { _id: 'QgwmBiEWyG4ad4vKL',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.16906179394572973,
    title: 'Lavašikrõpsud juustuga',
    formErrors: {},
    ingredients: 'Lavaš, juust, maitseained',
    foodType: 'main',
    price: 5,
    weight: 350,
    published: true },
  { _id: 'RApA36zFNd5wPEbdg',
    chefId: 'GXuYGobJtJq5THiZh',
    rand: 0.63820073264651,
    title: 'Serrano singi-meloni vardad',
    formErrors: {},
    ingredients: 'Serrano sink, melon, ruccola',
    foodType: 'main',
    weight: 50,
    published: true,
    price: 1.5 },
  { _id: 'RBQy2cpSc9S7z9ott',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.47290122089907527,
    title: 'Kookose-piparkoogi (lume)pallid vitamiiniüllatusega',
    formErrors: {},
    ingredients: 'Toorjuust, šokolaad, piparkoogid, kookoshelbed, jõhvikad, granaatõuna seemned',
    foodType: 'dessert',
    price: 0.8,
    weight: 30,
    published: true },
  { _id: 'RK2ichPFRSRmKLGQb',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.9861715915612876,
    title: 'Priske hakkliha-paprika pirukas juustuga',
    formErrors: {},
    ingredients: 'Või, jahu, muna, hakkliha, paprikas, juust, sibul, küüslauk, maitseained, tomat',
    foodType: 'main',
    weight: 90,
    published: true,
    price: 1.1 },
  { _id: 'RoQrgbRTiF9brmSMs',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.6098160441033542,
    title: 'Ahjus küpsetatud vürtsmandlid',
    formErrors: {},
    ingredients: 'Mandlid, munavalge, suhkur, maitseained',
    foodType: 'dessert',
    price: 6,
    weight: 220,
    published: true },
  { _id: 'RseWfPZ2PHcbuh9vx',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.9841764462180436,
    title: 'Õuna-martsipani kook mandlilaastudega',
    ingredients: 'Küpsised, või, fariinisuhkur, õunad, toorjuust, kohupiim, munad, martsipan, suhkur, mandlilaastud',
    foodType: 'dessert',
    published: true,
    formErrors: {},
    weight: 45,
    price: 1.1 },
  { _id: 'S7CqAiFWfQNKB9fGp',
    chefId: 'fwRMoa93LcF3PjvoP',
    rand: 0.10395268397405744,
    title: 'Ürdine peediruut',
    formErrors: {},
    ingredients: 'Peet, rosmariin, lepasuitsu- või kitsepiimajuust, lehttaigen',
    weight: 35,
    foodType: 'main',
    published: true,
    price: 0.8 },
  { _id: 'SP55jfae9cwYnWtMg',
    chefId: 'GfeKy92bg4y5KdJo4',
    rand: 0.7570508732460439,
    title: 'Kodujuustu köögiviljade õhuline kook ',
    formErrors: {},
    ingredients: 'Kodujuust, muna, hapukoor, köögiviljad (paprika, porru, porgand, lillkapsas, brokkoli), juust, või. ',
    foodType: 'main',
    weight: 35,
    published: true,
    price: 1.1 },
  { _id: 'SyFWqa9Trssx7H9Ej',
    chefId: 'GXuYGobJtJq5THiZh',
    ingredients: 'Jahu, muna, või, suitsukana, kinoa, paprika, kurk, seller, ürdid, oliivõli, oliivid, maitseained',
    formErrors: {},
    title: 'Profitroolid suitsukana-kinoa salatiga',
    foodType: 'main',
    weight: 70,
    published: true,
    price: 1.1 },
  { _id: 'TN2dPZ4ngcAvrxqDq',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.4664636617526412,
    title: 'Kodused lihapallid lehttaigna sõlmes (pulga otsas)',
    formErrors: {},
    ingredients: 'Hakkliha (70% mahe veiseliha, 30% sealiha), peet, sibul, porgand, maitseained, muna, riivsai, lehttainas',
    foodType: 'main',
    price: 0.7,
    weight: 22,
    published: true },
  { _id: 'TdZiaS99Hc4GLodMv',
    chefId: 'vW7xv5Ckjmy2wSbie',
    rand: 0.5050950073637068,
    title: 'Veisepasteedi seemneleival',
    formErrors: {},
    ingredients: 'Veisepasteet, tüümian, muskaat, maitseroheline, seemneleib',
    foodType: 'main',
    price: 1,
    weight: 30,
    published: true },
  { _id: 'Wa3RibJTuMAR8HtPo',
    chefId: 'GXuYGobJtJq5THiZh',
    title: 'Vürtsikiluvaht mustal leival pähklipuru ja ürtidega',
    formErrors: {},
    ingredients: 'Vürtsikilu, toorjuust, leib, pähklid, värsked ürdid, maitseained',
    foodType: 'main',
    weight: 40,
    published: true,
    price: 0.8 },
  { _id: 'WaxF3WvEdHjzGmFcS',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.83456821157597,
    title: 'Jõulumaitseline pohlakeeks pähklitega',
    ingredients: 'Või, jahu, munad (vabalt peetud kanade omad), küpsetuspulber, suhkur, mesi, kreeka pähklid, mandlid, pohlad, hapukoor',
    foodType: 'dessert',
    published: true,
    formErrors: {},
    weight: 35,
    price: 1.1 },
  { _id: 'XpCYewCwyFXq5s8aX',
    chefId: 'GXuYGobJtJq5THiZh',
    title: 'Rulaad krõbesaial ürdivõi ja jõhvika tarretisega',
    formErrors: {},
    ingredients: 'Kana või sealiharulaad, krõbesai, või, ürdid, tarretis, maitseained',
    foodType: 'main',
    weight: 30,
    published: true,
    price: 0.8 },
  { _id: 'YgdwWTtDSEom8A32E',
    chefId: 'GfeKy92bg4y5KdJo4',
    title: 'Hapuoblika-peekoni pirukas',
    formErrors: {},
    ingredients: 'Hapuoblikas, peekon, nisujahu, pärm, või, juust, majonees, suhkur, sool. ',
    foodType: 'main',
    weight: 100,
    published: true,
    price: 0.8 },
  { _id: 'Z75i6KScvGfXTRSMW',
    chefId: 'GfeKy92bg4y5KdJo4',
    rand: 0.5991410175338387,
    title: 'Verikäkk peekoni ja sulatatud juustu vahuga ',
    formErrors: {},
    ingredients: 'Verikäkk, sulatatud juust, peekon, chilli, tomat',
    weight: 30,
    foodType: 'main',
    published: true,
    price: 0.8 },
  { _id: 'ZYXwGi2JrutwBfiqX',
    chefId: 'GfeKy92bg4y5KdJo4',
    title: 'Mädarõika-peedi vaht koduleival seakeelega',
    formErrors: { managerComments: 'Palun täida ka see väli' },
    ingredients: 'Täistera kodu rukkileib seemnetega (juuretisega), mädarõigas, peet, toorjuust, seakeel, sool, pipar.',
    foodType: 'main',
    weight: 35,
    published: true,
    price: 1.1,
    managerComments: ''},
  { _id: 'ZtmRpN5BFjZkLEpZi',
    chefId: 'GXuYGobJtJq5THiZh',
    title: 'Seene-spinati quiche Cheddar juustu kattega',
    formErrors: {},
    ingredients: 'Muna, koor, jahu, või, parmesan, cheddar, shampinjonid, spinat, küüslauk, maitseained',
    foodType: 'main',
    weight: 80,
    published: true,
    price: 1.5},
  { _id: 'a5qMN6FRiTDBjt4jH',
    chefId: 'GfeKy92bg4y5KdJo4',
    rand: 0.9034590444061905,
    title: 'Praetud part köögiviljadega riisipaberis balsamico-mees-sidruni kastmega',
    formErrors: {},
    ingredients: 'Part, uba, idud, porru, balsamico, sidrun, mesi',
    price: 1.5,
    foodType: 'main',
    weight: 35,
    published: true },
  { _id: 'a8RF448TL6NjkGsAs',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.798560572322458,
    title: 'Shampinjoni-singi minipitsa',
    formErrors: {},
    ingredients: 'Pärmitainas, shampinjonid, sink, sibul, porru,  tomatipasta, juust, maitseained',
    foodType: 'main',
    weight: 20,
    published: true,
    price: 0.8 },
  { _id: 'aqoWYhEHuyPGwj2ea',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.5680710880551487,
    title: 'Kass Arturi pallid',
    formErrors: {},
    ingredients: 'Maisipallid, või, iirised',
    foodType: 'dessert',
    price: 0.8,
    weight: 35,
    published: true},
  { _id: 'awk4qvACKomFyuPq9',
    chefId: 'vW7xv5Ckjmy2wSbie',
    title: 'Kilu-kappari munavahuga',
    formErrors: {},
    ingredients: 'Vürtsikilu, munavaht, seemneleib, maitseroheline, suur kapparimari',
    foodType: 'main',
    weight: 40,
    published: true,
    price: 1.1},
  { _id: 'c7YNWvQCjQoMnp6MS',
    chefId: 'GfeKy92bg4y5KdJo4',
    title: 'Vürtsikilu munavõidega kodusel seemnetega rukkileival',
    formErrors: {},
    ingredients: 'Rukkileib (juuretisega), kodune hapukurk, suitsuliha, toorjuust.',
    foodType: 'main',
    weight: 35,
    published: true,
    price: 0.8},
  { _id: 'c97r3GpRgp5GS4ybJ',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.8466262214351445,
    title: 'Piparkoogipõhjal kohupiimakook mandlikattes',
    ingredients: 'Piparkoogid, fariinisuhkur, või, kohupiim, hapukoor, munad, suhkur, vanillisuhkur, mandlilaastud',
    foodType: 'dessert',
    published: true,
    formErrors: {},
    weight: 55,
    price: 1.1 },
  { _id: 'cPBJbevcMYwMExLGs',
    chefId: 'GXuYGobJtJq5THiZh',
    rand: 0.8304785070940852,
    title: 'Lastemenüü 98€',
    formErrors: {},
    ingredients: '1. Muumiad (viineripirukas)\n2. Kaheksajalad ründavad (viineritest kaheksajalad, kodune kartulisalat või makaronisalat, serveering eraldi topsides)\n3. Ulpivad meremiinid (lihapall, tomatikaste, serveering eraldi topsides)\n4. Värvilised vägipulgad (paprika, valge redis, porgand, värske kurk, kaste, serveering eraldi topsis)\n5. Kirju Koer (küpsis, marmelaad, shokolaad, või, kondenspiim)\n6. Vahupommid (vahukomm, valge + piimashokolaad, nonparellid, pulga otsas)',
    foodType: 'main',
    weight: 250,
    published: true,
    price: 0.8 },
  { _id: 'ccapBAya58ExPCvJ9',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.89984748698771,
    title: 'Rulli keeratud taimne minipitsa',
    formErrors: {},
    ingredients: 'Pärmi/pärmi-lehttaigen, või, maitseained-ürdid, tomatipasta, pesto, juust, seesamiseemned',
    foodType: 'main',
    price: 1,
    weight: 30,
    published: true },
  { _id: 'cifgRSQLcaHFiongT',
    chefId: 'GfeKy92bg4y5KdJo4',
    rand: 0.5554293501190841,
    title: 'Suitsulõhe vaht kodusel kukklil',
    formErrors: {},
    ingredients: 'Suitsulõhe, toorjuust, kodune nisujahukukkel, kodune hapukurk või meremari garneeringuks',
    weight: 30,
    foodType: 'main',
    published: true,
    price: 0.8 },
  { _id: 'd7da4tbFJHLMiwt32',
    chefId: 'WQzN4N8LdwBNGzzZ5',
    rand: 0.490746678551659,
    title: 'Patuvabad rummipallid',
    formErrors: {},
    ingredients: 'Dattel, mandel, kookos, kakao, rummiessents',
    foodType: 'dessert',
    weight: 30,
    published: true,
    price: 0.8 },
  { _id: 'dAf6u9NFydm7uiheu',
    chefId: 'GfeKy92bg4y5KdJo4',
    rand: 0.6472339339088649,
    title: 'Suitsusingi-koduse hapukurgi vaht kodusel rukkileival',
    formErrors: {},
    ingredients: 'Suitsusink, kodune hapukurk, toorjuust, kodune rukkileib',
    foodType: 'main',
    weight: 30,
    published: true,
    price: 0.8 },
  { _id: 'dCBtJw4vzLMF2BTbz',
    chefId: 'GfeKy92bg4y5KdJo4',
    title: 'Britta kook',
    formErrors: {},
    ingredients: 'Muna, jahu, või, piim, suhkur, mandlilaastud, vahukoor, kohupiim, marjad',
    foodType: 'dessert',
    weight: 90,
    published: true,
    price: 1},
  { _id: 'dXRPTns6rXunGoNc7',
    chefId: 'GXuYGobJtJq5THiZh',
    ingredients: 'Jahu, muna, või, suitsukala, bulgur, paprika, kurk, mais, ürdid, majonees, maitseained',
    formErrors: {},
    title: 'Profitroolid hõrgu suitsukala- ja bulgurisalatiga',
    foodType: 'main',
    weight: 50,
    published: true,
    price: 0.8 },
  { _id: 'dhbFNdp9aCNdr8Jpz',
    chefId: 'fwRMoa93LcF3PjvoP',
    rand: 0.29122578958049417,
    ingredients: 'Hannes ei tea hetkel',
    formErrors: {},
    title: 'Kõrvitsa-banaani pannkoogid vaarika toormoosiga',
    weight: 15,
    price: 0.3,
    foodType: 'dessert',
    published: true },
  { _id: 'dstxtcHwzcoySPQui',
    chefId: 'GfeKy92bg4y5KdJo4',
    rand: 0.9357438089791685,
    title: 'Brie suupiste ingveri-apelsiini moosiga ciabattal',
    formErrors: {},
    ingredients: 'Brie juust, ingver, apelsin, ciabatta',
    foodType: 'main',
    weight: 35,
    published: true,
    price: 1.1 },
  { _id: 'eaRtkyYwXzBqpKFZS',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.06398401688784361,
    title: 'Näkileivarullide duo toorjuustu-ürdi täidisega',
    ingredients: 'Näkileivad, puljong, toorjuust, ürdid, maitseained, hapukoor',
    foodType: 'main',
    weight: 25,
    published: true,
    formErrors: {},
    price: 0.8 },
  { _id: 'em3QSxzfJDqcrCun2',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.042187623446807265,
    title: 'Jõulune šokolaadi-aplesini kook',
    formErrors: {},
    ingredients: 'Või, jahu (nisu- ja täistera nisujahu), suhkur, munad,apelsin, šokolaad, mandlid, maitseained, vürtsid',
    foodType: 'dessert',
    weight: 35,
    published: true,
    price: 0.8 },
  { _id: 'eumSKqzY8Qx69MPpp',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.1537690192926675,
    title: 'Singi-juustu roos',
    formErrors: {},
    ingredients: 'Lehttainas, sink, juust, maitseained, või',
    foodType: 'main',
    price: 0.8,
    weight: 25,
    published: true },
  { _id: 'exYdehJNDHiA35NMc',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.437539872713387,
    title: 'Mustika-šokolaadi kook kooskoshelveste või mandlilaastudega',
    ingredients: 'Küpsised, suhkur, või, toorjuust, hapukoor, mustikad, tume šokolaad, munad, kookoshelbed või mandlilaastud',
    foodType: 'dessert',
    published: true,
    formErrors: {},
    weight: 60,
    price: 1.5 },
  { _id: 'f5hF82JFjBRpq6dr2',
    chefId: 'fwRMoa93LcF3PjvoP',
    rand: 0.24185119289904833,
    title: 'Suvikõrvitsa-riisi pirukas',
    formErrors: {},
    ingredients: 'Suvikõrvits, riis, muna, juust, gluteenivaba jahusegu',
    foodType: 'main',
    weight: 45,
    published: true,
    price: 1.1 },
  { _id: 'fCxo3PD89E8LAgwns',
    chefId: 'GXuYGobJtJq5THiZh',
    title: 'Lihavardad värviliste aedviljadega BBQ glasuuris',
    formErrors: {},
    ingredients: 'Kana või sealiha, zuccini, paprika, shampinjonid, BBQ kaste, maitseained',
    foodType: 'main',
    weight: 90,
    published: true,
    price: 1.5 },
  { _id: 'fMYYskQpGoHsZGNs8',
    chefId: 'GfeKy92bg4y5KdJo4',
    rand: 0.19873722991906106,
    title: 'Sinihallitusjuustuga täidetud kuivatatud ploomid, mis keeratud peekoni sisse 10 tükki',
    formErrors: {},
    ingredients: 'Sinihallitusjuust, peekon, kuivatatud ploomid',
    managerComments: '',
    weight: 150,
    price: 6,
    foodType: 'main',
    published: true },
  { _id: 'fSEHtBZNsx9rFKY4m',
    chefId: 'GfeKy92bg4y5KdJo4',
    rand: 0.21082773245871067,
    title: 'Värske salat erinevate salatilehtedega, koos avokaado, meloni, värske kurgi ja pirniga',
    formErrors: {},
    price: 15,
    weight: 1000,
    foodType: 'main',
    ingredients: ' erinevate salatilehtedega, koos avokaado, meloni, värske kurgi ja pirniga',
    published: true },
  { _id: 'fYLobzs3PHtah6zdx',
    chefId: 'fwRMoa93LcF3PjvoP',
    rand: 0.718748124781996,
    title: 'Kukeseenepasteet rukkileivaõiel ',
    formErrors: {},
    ingredients: 'Kukeseened,  sibul, pastinaak,  baklažaan, oliivõli',
    foodType: 'main',
    weight: 25,
    published: true,
    price: 0.8 },
  { _id: 'gJsXDyyjTMZ4P7XTS',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.18366224551573396,
    ingredients: 'Pärmitainas, shampinjonid, sinihallitusjuust, sibul, pesto, juust, maitseained',
    formErrors: {},
    title: 'Minipitsa seente ja sinihallitusjuustuga',
    foodType: 'main',
    weight: 20,
    published: true,
    price: 0.8 },
  { _id: 'gQDKJZbg2DWC4tMNJ',
    chefId: 'vW7xv5Ckjmy2wSbie',
    title: 'Hõbeheigisalat lavašikorvis',
    formErrors: {},
    ingredients: 'Hõbeheik, muna, lavašikorvike, p.sibul, maitseroheline',
    foodType: 'main',
    weight: 40,
    published: true,
    price: 1.5},
  { _id: 'gcSupaqZneu3h6JwH',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.6509476583451033,
    title: 'Pirnisiil magusate okastega',
    formErrors: {},
    ingredients: 'Pirn, melon/maasikas, viinamari, füüsal',
    foodType: 'dessert',
    price: 5,
    weight: 200,
    published: true },
  { _id: 'hMjLfrBRyk67kNw5E',
    chefId: 'GXuYGobJtJq5THiZh',
    title: 'Juustuvahused singirullid mustal leival ürdivõi ja päikesekuivatatud kirsstomatitega',
    formErrors: {},
    ingredients: 'Juust, toorjuust, majonees, sink, või, leib, ürdid, kirsstomatid, salatiroheline',
    foodType: 'main',
    weight: 90,
    published: true,
    price: 1.1 },
  { _id: 'hNyYeEktrAcX383z2',
    chefId: 'GfeKy92bg4y5KdJo4',
    rand: 0.935167487245053,
    title: 'Glasuuriga kaunistatud kodused piparkoogid',
    formErrors: {},
    weight: 100,
    foodType: 'dessert',
    ingredients: 'Suhkur, või, nisujahu, vesi, sooda, piparkoogimaitseained. Glasuuris kasutatud erinevaid naturaalseid tooraineid. ',
    published: true,
    price: 1.5 },
  { _id: 'jbtZcRSoEwgcJtpwG',
    chefId: 'fwRMoa93LcF3PjvoP',
    rand: 0.2970425619278103,
    title: 'Spinatiquiche ',
    formErrors: {},
    ingredients: 'Spinat, sibul, riis, kirsstomatid,  gluteenivaba jahu, creme fraiche,  muna ja juust',
    foodType: 'main',
    weight: 110,
    published: true,
    price: 1.5 },
  { _id: 'kbkwqgZ3LDAXv4pf3',
    chefId: 'GfeKy92bg4y5KdJo4',
    rand: 0.8745300902519375,
    title: 'Miniverivorst peekonis mustsõstrasinepi ja marineeritud rohelise tomatiga kodusel rukkileival',
    formErrors: {},
    ingredients: 'Verivorst, peekon, mustsõstrasinep, marineeritud tomat',
    foodType: 'main',
    weight: 30,
    published: true,
    price: 1.1 },
  { _id: 'mQQxGXWS68yfm69KL',
    chefId: 'GfeKy92bg4y5KdJo4',
    rand: 0.032928138272836804,
    title: 'Avokaadovaht krevettidega kodusel rukkileival',
    formErrors: {},
    ingredients: 'Avokaado, krevetid, kodune rukkileib',
    foodType: 'main',
    weight: 35,
    published: true,
    price: 1.1 },
  { _id: 'o5pAYcFeK5fzxiNJZ',
    chefId: 'GfeKy92bg4y5KdJo4',
    rand: 0.17704242491163313,
    title: 'Riisi-makrasalat',
    formErrors: {},
    price: 7,
    weight: 1000,
    foodType: 'main',
    ingredients: 'riis, makra, värske kurk, mais, majonees, hapukoor',
    managerComments: '',
    published: true },
  { _id: 'oJb9vnpaywmnKJBuh',
    chefId: 'GXuYGobJtJq5THiZh',
    title: 'Rohelise herne pasteet krõbesaial Serrano sinigi ja parmesani krõpsuga',
    formErrors: {},
    ingredients: 'Jahu, muna, herned, tahini, toorjuust, sibul, serrano sink, parmesan, maitseained',
    foodType: 'main',
    weight: 25,
    published: true,
    price: 1.1 },
  { _id: 'om8vJ55vRBgXbSu99',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.45818329486064613,
    title: 'Juurikapulkadega dipitops',
    formErrors: {},
    ingredients: 'Paprika, porgand, kurk, hapukoor, maitseained',
    foodType: 'main',
    price: 1,
    weight: 50,
    published: true },
  { _id: 'pD37P56Z3m33hQJw4',
    chefId: 'GXuYGobJtJq5THiZh',
    title: 'Jalapeno quiche ',
    formErrors: {},
    ingredients: 'Jahu, muna, või, jalapeno, juust, ürdid, kohvikoor, peekon/sink, maitseained',
    foodType: 'main',
    weight: 110,
    published: true,
    price: 1.5 },
  { _id: 'qCFqrYNNwnWXqrpPi',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.12854890571907163,
    title: 'Minipitsa hakkliha ja paprikaga',
    formErrors: {},
    ingredients: 'Pärmitainas, hakkliha, sibul, paprika, päikesekuivat. tomat, tomatipasta, juust, maitseained',
    weight: 25,
    foodType: 'main',
    published: true,
    price: 0.8 },
  { _id: 'qLSGzTsT75nLdGZLB',
    chefId: 'GXuYGobJtJq5THiZh',
    title: 'Sinihallitusjuustuvaht piparkoogi ja pirniga',
    formErrors: {},
    ingredients: 'Sinihallitusjuust, toorjuust, kreeka pähklid, piparkook, pirn',
    foodType: 'main',
    weight: 35,
    published: true,
    price: 0.8 },
  { _id: 'qjjHEK3SegMsxLu7z',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.031633156118914485,
    title: 'Tuunikala muffinid oliividega',
    ingredients: 'Jahu, või, küpsetuspulber, hapukoor, oliivid, tuunikala, porru, juust, maitseained',
    foodType: 'main',
    published: true,
    formErrors: {},
    weight: 40,
    price: 0.8 },
  { _id: 'qktYXFtPZbi4NFB6K',
    chefId: 'WQzN4N8LdwBNGzzZ5',
    rand: 0.7269034320488572,
    title: 'Rabarberitäidisega kook siidise mascarpone kohupiima kattega',
    formErrors: {},
    ingredients: 'Muretainas (ise tehtud, sisaldab võid ja muna), mascarpone, rabarber, suhkur, maisitärklis',
    foodType: 'dessert',
    weight: 80,
    published: true,
    price: 1.1},
  { _id: 'qyt7szRBtueDBLkmo',
    chefId: 'GfeKy92bg4y5KdJo4',
    rand: 0.20334999519400299,
    title: 'Kartulisalat lavashi korvis',
    formErrors: {},
    ingredients: 'Kartul, porgand, hernes, muna, marineeritud kurk, majonees, hapukoor, lavash',
    price: 1,
    foodType: 'main',
    weight: 40,
    published: true },
  { _id: 'rDPxbSQusvCgZG8J4',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.9100677608512342,
    title: 'Heeringa/vürtsikilu leivatort ürdirohke katusega',
    formErrors: { foodType: null },
    ingredients: 'Must leib, või, toorjuust, hapukoor, vürtsikilu/heeringas, hapukurk, želatiin, ürdid, maitseained',
    foodType: 'main',
    weight: 45,
    published: true,
    price: 0.8 },
  { _id: 'rSDZKDtrjDBrJ8sfW',
    chefId: 'vW7xv5Ckjmy2wSbie',
    rand: 0.9348544843960553,
    title: 'Maasingikreem seemneleival',
    formErrors: {},
    ingredients: 'Maasingi-toorjuustukreem, maitseroheline, seemneleib',
    foodType: 'main',
    price: 1,
    weight: 30,
    published: true },
  { _id: 's5kKKcBzKi65c5R9d',
    chefId: 'GfeKy92bg4y5KdJo4',
    rand: 0.7818697863258421,
    title: 'Bulguri-suitsukana salat tuuletaskus',
    formErrors: {},
    ingredients: 'Bulgur, suitsukana, majonees, maitseroheline, paprika, nisujahu, muna, või.',
    foodType: 'main',
    price: 1.1,
    weight: 40,
    published: true },
  { _id: 's6yCArG5ycQzm8367',
    chefId: 'GXuYGobJtJq5THiZh',
    rand: 0.15550944884307683,
    title: 'Lavashirull lumekrabist',
    formErrors: {},
    ingredients: 'Makra/lumekrabi, helmanns majonees, paprika, kurk, lavash, sinep, salat',
    foodType: 'main',
    weight: 50,
    published: true,
    price: 0.8 },
  { _id: 'sJ6BsdHAobwGWCmHp',
    chefId: 'GfeKy92bg4y5KdJo4',
    rand: 0.8504209858365357,
    title: 'Soolalõhe lavashirull',
    formErrors: {},
    ingredients: 'Soolalõhe, lavash, toorjuust, meremari, kodune hapukurk',
    weight: 30,
    foodType: 'main',
    published: true,
    price: 1.1 },
  { _id: 'stYT4669xrz2nPugk',
    chefId: 'GXuYGobJtJq5THiZh',
    title: 'Naked burger ',
    formErrors: {},
    ingredients: 'Looma-ja seahakkliha, muna, ürdid, salatileht, kirsstomat, kurk, laktoosivaba toorjuust, idandid',
    foodType: 'main',
    weight: 60,
    published: true,
    price: 1.1 },
  { _id: 't8qjFEy3XT6He2bm3',
    chefId: 'GfeKy92bg4y5KdJo4',
    rand: 0.3088130939286202,
    title: 'Pastasalat oa-suitsukana ja ananassiga',
    formErrors: {},
    ingredients: 'Pasta, konserveeritud oad, suitsukana, ananass, majonees, hapukoor, sool, pipar',
    weight: 1000,
    foodType: 'main',
    price: 8,
    published: true },
  { _id: 'tzFCS5nR6RjrksXag',
    chefId: 'vW7xv5Ckjmy2wSbie',
    title: 'Riisika-toorjuustu lavašikorvis',
    formErrors: {},
    ingredients: 'Riisikad,toorjuust, p.sibul,  maitseroheline ,lavašikorvike',
    foodType: 'main',
    weight: 40,
    published: true,
    price: 1.3},
  { _id: 'u6ia5vhPyJgTyefXv',
    chefId: 'WQzN4N8LdwBNGzzZ5',
    rand: 0.006255334941670299,
    title: 'Täisterakaerahelbe küpsis kuivatatud jõhvikate ja kõrvitsaseemnetega',
    formErrors: {},
    ingredients: 'Täisterakaerahelbejahu, majonees, pruun suhkur, sooda, kuivatatud jõhvikad, kõrvitsaseemned',
    foodType: 'dessert',
    weight: 30,
    published: true,
    price: 0.8 },
  { _id: 'uZYHgxdtikzxzbY9Y',
    chefId: 'GXuYGobJtJq5THiZh',
    ingredients: 'Jahu, muna, või, suitsukana, kinoa, paprika, kurk, seller, ürdid, majonees, maitseained',
    formErrors: {},
    title: 'Profitroolid suitsukana- kinoasalatiga',
    foodType: 'main',
    weight: 50,
    published: true,
    price: 0.8 },
  { _id: 'uqfwusSimZjxirFDh',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.574981291545555,
    title: 'Laimi-tšill-kookose toorjuustukook',
    ingredients: 'Küpsised, kookoshelbed, või, suhkur, laimi koor ja mahl, toorjuust, želatiin või agar-agar, tšilli',
    foodType: 'dessert',
    weight: 60,
    published: true,
    formErrors: {},
    price: 1.5 },
  { _id: 'urhiRyNMcBWQBHyCt',
    chefId: 'GfeKy92bg4y5KdJo4',
    rand: 0.4013403707649559,
    title: 'Kodujuustu-jalopeno terav minipirukas',
    formErrors: {},
    ingredients: 'Jalopeno, kodujuust, juust, muna, jalopeno, sool',
    price: 1.5,
    foodType: 'main',
    weight: 55,
    published: true },
  { _id: 'uzrFXSvbXexoQQkQ6',
    chefId: 'WQzN4N8LdwBNGzzZ5',
    rand: 0.16626187856309116,
    title: 'Pizzarullid',
    formErrors: {},
    ingredients: 'Pärmi-lehttaigen, juust, sink või suitsuvorts, ketsup/tomatipasta',
    foodType: 'main',
    weight: 70,
    published: true,
    price: 0.8 },
  { _id: 'v3ckWGithZzG4iX2K',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.9638456404209137,
    title: 'Seemnetulvaga kodune rukkileib ',
    ingredients: 'Täistera rukkijahu, juuretis, vesi, sool, suhkur (või mesi), erinevad seemned, soovi korral rosinad, või päikesekuvatatud tomatid või ploomid.',
    foodType: 'main',
    weight: 40,
    published: true,
    price: 0.8 },
  { _id: 'vM4wSSEqeC4gN4C5r',
    chefId: 'GXuYGobJtJq5THiZh',
    rand: 0.8487637753132731,
    title: 'Supp',
    formErrors: {},
    ingredients: 'Supp kliendiga kokkuleppel - püree / lihasupp /puljong  vms',
    foodType: 'main',
    weight: 200,
    published: true,
    price: 1.5 },
  { _id: 'vrgDfNzmpwjwFsjCb',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.13416447304189205,
    title: 'Juurvilja-hakkliha lihapallid ',
    formErrors: {},
    ingredients: 'Hakkliha (70% mahe veiseliha, 30% sealiha), peet, sibul, porgand, maitseained, muna, riivsai',
    foodType: 'main',
    price: 0.5,
    weight: 20,
    published: true },
  { _id: 'w3w3CqvKbqyLeAwbE',
    chefId: 'vW7xv5Ckjmy2wSbie',
    rand: 0.8835943294689059,
    title: 'Itaalia singi-pestotoorjuustukorvike',
    formErrors: {},
    ingredients: 'pesto-toorjuust, lavašikorv, itaalia sink, maitseroheline',
    price: 1.3,
    foodType: 'main',
    weight: 40,
    published: true },
  { _id: 'wJ44vkpva7AFjsFEY',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.44648830592632294,
    title: 'Kookospiimas marineeritud ja ahjus küpsetatud kananagitsad',
    formErrors: {},
    ingredients: 'Kanaliha, kookospiim, kookoshelbed, maitseained, riivsai',
    foodType: 'main',
    price: 0.5,
    weight: 18,
    published: true },
  { _id: 'wiNibJF9b4F9C6Ckm',
    chefId: 'GfeKy92bg4y5KdJo4',
    rand: 0.27468833327293396,
    title: 'Bulguri suitsukana salat köögiviljadega',
    formErrors: {},
    ingredients: 'Bulgur, suitsukana, erinevad köögiviljad, õli',
    price: 12,
    weight: 1000,
    foodType: 'main',
    published: true },
  { _id: 'wneDWDjSi96MtBNc9',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.2776453490369022,
    title: 'Vaarika-valge šokolaadi-kookose juustukook muffinivormis',
    ingredients: 'Küpsised, suhkur, või, toorjuust, hapukoor, vaarikad, valge šokolaad, munad, kookoshelbed',
    foodType: 'dessert',
    published: true,
    formErrors: {},
    weight: 60,
    price: 1.5 },
  { _id: 'wrHvjnuJcKNavx5vn',
    chefId: 'WQzN4N8LdwBNGzzZ5',
    rand: 0.40719026885926723,
    title: 'Kohupiima-ricotta-mascarpone plaadikook mustikate ja vaarikatega, peal virsik ja tumeshokolaad',
    formErrors: {},
    ingredients: 'Muretainas(ise tehtud), või, kohupiim, ricotta kohupiim, mascarpone, muna, pruun suhkur, mustikad (ise korjatud), vaarikad (oma aiast), kompoti virsik, purustatud tume shokolaad',
    foodType: 'dessert',
    weight: 100,
    published: true,
    price: 1.1 },
  { _id: 'xJquBTpT8cWRK5BRG',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.6703490663785487,
    formErrors: {},
    title: 'Rulli keeratud minipitsa (pulga otsas)',
    ingredients: 'Pärmi/pärmi-lehttaigen, või, maitseained, tomatipasta, sink, peekon, juust',
    foodType: 'main',
    price: 1,
    weight: 30,
    published: true },
  { _id: 'xgZim5Ds8DFJ42RhY',
    chefId: 'GfeKy92bg4y5KdJo4',
    rand: 0.24076108494773507,
    foodType: 'main',
    formErrors: {},
    price: 3,
    weight: 150,
    ingredients: 'Kana, tortilla salat',
    title: 'Kanatoritilla',
    published: true },
  { _id: 'xwFGGhj2F2cGDptct',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.5884698294103146,
    title: 'Suitsukana-aprikoosi pall kodusel seemneleival',
    formErrors: {},
    ingredients: 'Leib (juuretis, maitseained, seemned-rosinad), toorjuust/või, kurk, kuivatatud aprikoosid, suitsukana, seesamiseemned, maitseained, ürdid.',
    foodType: 'main',
    weight: 45,
    published: true,
    price: 0.8 },
  { _id: 'y3CqNaBRKw7Te4u2P',
    chefId: 'WQzN4N8LdwBNGzzZ5',
    rand: 0.5489992022048682,
    title: 'Grillvõileib rukkisepikust mozzarella virsiku ja tomatiga, pisukese balsamico ja tüümianiga',
    formErrors: {},
    ingredients: 'Rukkisepik, mozzarella, tomat, virsik, balsamico, tüümian',
    foodType: 'main',
    price: 0.8,
    weight: 30,
    published: true },
  { _id: 'yBrADQhgTzFRNjiEZ',
    chefId: 'GfeKy92bg4y5KdJo4',
    rand: 0.1707421294413507,
    title: 'Tuunikala lavashirull',
    formErrors: {},
    ingredients: 'Tuunikala, värske paprika, värske kurk, jääsalat, toorjuust, meremari, pipar',
    foodType: 'main',
    weight: 25,
    published: true,
    price: 0.8 },
  { _id: 'yEbp55sgWacdZRsDb',
    chefId: 'GXuYGobJtJq5THiZh',
    rand: 0.9047078499570489,
    ingredients: 'Looma-ja seahakkliha, muna, jahu, ürdid, salatileht, marineeritud kurk, coleslaw salat, cheddar juust',
    formErrors: {},
    title: 'Lõuna burger',
    foodType: 'main',
    weight: 80,
    published: true,
    price: 1.5 },
  { _id: 'yTqrrtjjWomapnZvi',
    chefId: 'BQb8naZoFmAZ5jHxt',
    rand: 0.3147943352814764,
    title: 'Pirnisiil soolaste okastega',
    formErrors: {},
    ingredients: 'Pirn, juust, kirsstomat/kurk',
    foodType: 'main',
    price: 5,
    weight: 200,
    published: true },
  { _id: 'yxWDAWSTEhbtnBNJC',
    chefId: 'GfeKy92bg4y5KdJo4',
    rand: 0.6870310965459794,
    title: 'Sinihallitusjuustu vaht sibulamoosi padjal kodusel kukklil',
    formErrors: {},
    ingredients: 'Sinihallitusjuust, nisujahu, pärm, sibul, balsamico, sool, suhkur, veiniäädikas, chilli',
    foodType: 'main',
    weight: 30,
    published: true,
    price: 1.1 } ]

    var changed = 0
    var skipped = 0
    insertItems.forEach(item => {
        if (!item.price) return
        var menuitem = MenuitemTemplates.findOne({_id: item._id, price: {$ne: item.price}, weight: {$ne: item.weight}})
        if (menuitem) {
            changed++
            console.log("NOW ", menuitem.price, menuitem.weight);
            console.log("THEN", item.price, item.weight);
            item.publishDate = new Date("2016-01-27")
            var update = {$addToSet: {history: item}}
            var set = {publishDate: new Date("2016-01-27")}
            if (!menuitem.publishDate)
                update.$set = set
            MenuitemTemplates.update(item._id, update)
        } else
            skipped++
    })
    console.log("changed", changed);
    console.log("skipped", skipped);

});
